version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /family-chores
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /health-tracker
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /notes-app
    schedule:
      interval: weekly
